<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img.Item</name>
   <tag></tag>
   <elementGuidId>bc93214e-e434-4fda-bbe3-fe8589739cdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://diagnostics.sandbox.arcadier.io/images/items/item-33706-637368586838029129-jxdlb3.jpg')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.item-big-img.load-area-img-tag</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://diagnostics.sandbox.arcadier.io/images/items/item-33706-637368586838029129-jxdlb3.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-big-img load-area-img-tag</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;item-detail-page  pace-done&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;item-details&quot;]/div[@class=&quot;item-detail-content&quot;]/div[1]/div[@class=&quot;item-detail-right&quot;]/div[@class=&quot;manege-affix affix-top&quot;]/div[@class=&quot;preview-image item-image&quot;]/div[@class=&quot;loadarea&quot;]/a[@class=&quot;load-area-a-tag&quot;]/img[@class=&quot;item-big-img load-area-img-tag&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://diagnostics.sandbox.arcadier.io/images/items/item-33706-637368586838029129-jxdlb3.jpg')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/div/div/div/a/img</value>
   </webElementXpaths>
</WebElementEntity>
